### ISSUE TITLE
我用 '--features', 'MS',的时候，怎么解决

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/iTransformer#155]
Traceback (most recent call last):
  File "run.py", line 135, in <module>
    exp.test(setting)
  File "C:\Users\ZRCC\Desktop\kk\iTransformer-main\iTransformer-main\experiments\exp_long_term_forecasting.py", line 235, in test
    outputs = test_data.inverse_transform(outputs.squeeze(0)).reshape(shape)
  File "C:\Users\ZRCC\Desktop\kk\iTransformer-main\iTransformer-main\data_provider\data_loader.py", line 98, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "F:\shuoAPP\anaconda\envs\itr\lib\site-packages\sklearn\preprocessing\_data.py", line 1052, in inverse_transform
    X *= self.scale_
ValueError: non-broadcastable output operand with shape (96,1) doesn't match the broadcast shape (96,7)

**Comment by xiaobos1** [comment]
降低参数中的，如seq_len = 94 => 48 label_len = 48=>24  pred_len = 96=>24
--seq_len
--label_len
--pred_len
