### ISSUE TITLE
很期待您回复，我在这 主要将改为 '--features', 'MS', 和改parser.add_argument('--inverse', default=True)，然后报错怎么改

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/iTransformer#156]
command = [
    'python', '-u', 'run.py',
    '--is_training', '1',
    '--root_path', './dataset/ETT-small/',
    '--data_path', 'ETTh1.csv',
    '--model_id', 'ETTh1_96_96',
    '--model', model_name,
    '--data', 'ETTh1',
    '--features', 'MS',
    '--seq_len', '96',
    '--pred_len', '96',
    '--e_layers', '2',
    '--enc_in', '7',
    '--dec_in', '7',
    '--c_out', '7',
    '--des', 'Exp',
    '--d_model', '256',
    '--d_ff', '256',
    '--itr', '1'
]
Traceback (most recent call last):
  File "run.py", line 135, in <module>
    exp.test(setting)
  File "C:\Users\ZRCC\Desktop\kk\iTransformer-main\iTransformer-main\experiments\exp_long_term_forecasting.py", line 235, in test
    outputs = test_data.inverse_transform(outputs.squeeze(0)).reshape(shape)
  File "C:\Users\ZRCC\Desktop\kk\iTransformer-main\iTransformer-main\data_provider\data_loader.py", line 98, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "F:\shuoAPP\anaconda\envs\itr\lib\site-packages\sklearn\preprocessing\_data.py", line 1052, in inverse_transform
    X *= self.scale_
ValueError: non-broadcastable output operand with shape (96,1) doesn't match the broadcast shape (96,7)

**Comment by Learntodeath123** [comment]
楼上解决了吗我也遇到了

**Comment by THMAIL** [comment]
逆标准化失败了而已，你输出维度为96,1自然不可能直接使用96,7的scaler进行恢复，自己做个转换吧

**Comment by THMAIL** [comment]
用这个来做逆标准化吧    
def inverse_result(self, data):
        mean_last = self.scaler.mean_[-1]
        std_last = self.scaler.scale_[-1]
        return data * std_last + mean_last

**Comment by tang1tnag** [comment]
楼上解决这个问题了吗？我也遇到了逆归一化没法完成，不清楚如何改？能不能指点一下，具体在哪块代码下面怎么修改
