### ISSUE TITLE
Error when using a Custom dataset with weekly frequency

### ISSUE THREAD

**Issue by elenamanth** [thuml/iTransformer#60]
Hello! I have successfully run the iTransformer in a custom dataset with hourly, daily and monthly frequency with no problem. When trying to do the same for a weekly frequency i get the following error: 

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\collate.py", line 264, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "c:\Users\Anaconda3\envs\timeseries\lib\site-packages\torch\utils\data\_utils\collate.py", line 169, in collate_numpy_array_fn
    raise TypeError(default_collate_err_msg_format.format(elem.dtype))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object

**Comment by WenWeiTHU** [comment]
It seems to be a problem with the inconsistent number of variables returned by get_item. Since this issue is less relative to the paper, the issue will be closed.

**Comment by merickiranoglu** [comment]
I'm not really experienced with this method, but I'd like to share my experience with this issue.

Default value of start token length was causing this issue on my case, some examples overload the input seq_len and pred_len, but they skip label_len, but when label_len remains unrelated, pytorch throws the following error.
